### ISSUE TITLE
BUG: not mapping landmarks or expandng images that are larger file size

### ISSUE THREAD

**Issue by crazyGru** [HarmonyAI09/harmony_frontend#5]
![Image](https://github.com/HarmonyAI09/harmony_frontend/assets/157229524/08e6c770-2690-428b-92ad-2d940a679eec)

![Image](https://github.com/HarmonyAI09/harmony_frontend/assets/157229524/5ff6400d-2488-4552-b7c3-641ddb2b8fae)

**Comment by DitmarHoxha** [comment]
https://www.loom.com/share/a0e9a3ff44434206be8f00488f81175a

**Comment by crazyGru** [comment]
Not sure right now.
